server {
    listen 80;
    server_name localhost;
    root /var/www/html/public;

    index index.php index.html index.htm;

    # Règles pour gérer les requêtes vers les fichiers PHP
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # # Serve static files
    # location ~* \.(jpg|jpeg|gif|png|css|js|ico|svg)$ {
    #     try_files $uri /index.php?$query_string;
    #     expires 30d;
    #     access_log off;
    # }

    location /source/ {
        alias /var/www/html/public/source/;
        try_files $uri /index.php?$query_string;
        add_header Cache-Control no-cache;
        expires off;
    }



    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }

    location ~ \.env {
        deny all;
    }
}


